# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: file-spec 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "file-spec"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kristian Mandrup"]
  s.date = "2014-07-24"
  s.description = "RSpec 2 matchers for files, directories and symlinks"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "file-spec.gemspec",
    "lib/file-spec.rb",
    "lib/file_spec/file_helpers/test_dirs.rb",
    "lib/file_spec/file_helpers/test_files.rb",
    "lib/file_spec/file_helpers/test_symlinks.rb",
    "lib/file_spec/matchers/abstract/have_file_item.rb",
    "lib/file_spec/matchers/abstract/have_file_items.rb",
    "lib/file_spec/matchers/have_dir.rb",
    "lib/file_spec/matchers/have_file.rb",
    "lib/file_spec/matchers/have_symlink.rb",
    "spec/file-spec/matchers/multiple/have_directories_spec.rb",
    "spec/file-spec/matchers/multiple/have_files_spec.rb",
    "spec/file-spec/matchers/multiple/have_symlinks_spec.rb",
    "spec/file-spec/matchers/single/have_directory_spec.rb",
    "spec/file-spec/matchers/single/have_file_spec.rb",
    "spec/file-spec/matchers/single/have_symlink_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/file-spec"
  s.rubygems_version = "2.2.2"
  s.summary = "RSpec 2 matchers for files, directories and symlinks"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<rspec>, ["~> 3"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.1"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.9"])
    else
      s.add_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_dependency(%q<rspec>, ["~> 3"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.1"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<simplecov>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<require_all>, ["~> 1.2.0"])
    s.add_dependency(%q<rspec>, ["~> 3"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.1"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<simplecov>, ["~> 0.9"])
  end
end

